name: Run tests + Allure + Pages

on:
  push:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Install Playwright browsers
        run: poetry run playwright install --with-deps

      - name: Run tests (sample only)
        run: |
          mkdir -p reports
          poetry run pytest tests/test_sample.py \
            -v \
            --junitxml=reports/junit.xml \
            --alluredir=reports/allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre

          curl -L -o allure.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.tgz

          tar -xzf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure HTML report
        run: |
          allure generate reports/allure-results -o reports/allure-report --clean

      - name: Prepare Pages folder
        run: |
          rm -rf public
          mkdir -p public
          cp -r reports/allure-report/* public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
